Set errors = replace in open function calls
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 500: invalid start byte' was raised in 314. email received by whalley-g. For the scope of this exercise, we replace this byte.